# Generated by Django 3.2.4 on 2021-06-18 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0004_alter_servicenote_client'),
        ('profile_app', '0002_alter_useradditioninfo_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField()),
                ('service_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services_app.servicenote')),
            ],
        ),
    ]
