# Generated by Django 3.2.4 on 2021-06-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0004_alter_servicenote_client'),
        ('profile_app', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='service_note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='services_app.servicenote'),
        ),
    ]
