# Generated by Django 3.2.5 on 2021-07-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_feedback_service_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
