# Generated by Django 3.2.4 on 2021-06-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0004_alter_servicenote_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services_images/'),
        ),
    ]
