# Generated by Django 3.2.4 on 2021-07-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0005_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenote',
            name='addition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
