# Generated by Django 3.2.5 on 2021-07-12 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services_app', '0008_auto_20210709_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_app.service'),
        ),
    ]
