# Generated by Django 3.2.5 on 2021-07-12 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services_app', '0009_auto_20210712_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenote',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=models.SET(-1), related_name='provider', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicenote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(-1), related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
