# Generated by Django 3.2.5 on 2021-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0010_auto_20210712_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicenote',
            old_name='addition',
            new_name='provider_addition',
        ),
        migrations.AddField(
            model_name='servicenote',
            name='client_addition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
