# Generated by Django 3.2.5 on 2021-07-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0013_auto_20210726_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicenote',
            name='who_can_record',
        ),
        migrations.RemoveField(
            model_name='servicenote',
            name='who_can_see',
        ),
        migrations.AddField(
            model_name='service',
            name='who_can_record',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Авторизованные'), (2, 'Только я')], default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='who_can_see',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Авторизованные'), (2, 'Только я')], default=0),
        ),
    ]
