name: Pycodestyle

on: 
  push:
    branches:
    - develop
    - master
  workflow_dispatch:

jobs:
  codestyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle pylint
    - name: Analysing the code with pycodestyle
      continue-on-error: true
      run: |
        pycodestyle . --exclude=venv,migrations --statistics --max-line-length=80 --format=pylint
    - name: Analysing the code with pylint
      continue-on-error: true
      run: |
        echo `ls -R|grep .py$|xargs`
        pylint `ls -R|grep .py$|xargs`
